# Site settings
title: Elza Homestead
email: hayden.elza@gmail.com
description: > 
 Year round Aquaponic Greenhouse & Microgreens production. Seasonal SPIN farming.
 
 <br>

 We are a family homestead based business focused on local and sustainable food production. Although not certified, we use only natural and organic methods. We never us harmful pestisides, herbicides, chemicals, or GMOs. We believe in teaming up with nature while integrating new technologies. : )
 
 <br>

 Jared Elza - Elza Homestead

baseurl: ""
url: "localhost:4000" 
url: "elzahomestead.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
permalink: /:year/:month/:title
