# Site settings
title: Elza Homestead
email: hayden.elza@gmail.com
description: > 
  We are a family homestead based business specializing in local and sustainable food production. All of our produce is grown using natural and organic methods, we never use chemicals of any kind!
  <br><br>
  Jared Elza â€“ Homesteader

baseurl: "/blog"
url: "localhost:4000" 
url: "elzahomestead.com/blog/" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables","autolink","strikethrough","fenced_code_blocks","superscript","underline"]
permalink: /:year/:month/:title